// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
	model "tmf663/dao/model"
)

func newSHOPPINGCART(db *gorm.DB, opts ...gen.DOOption) sHOPPINGCART {
	_sHOPPINGCART := sHOPPINGCART{}

	_sHOPPINGCART.sHOPPINGCARTDo.UseDB(db, opts...)
	_sHOPPINGCART.sHOPPINGCARTDo.UseModel(&model.SHOPPINGCART{})

	tableName := _sHOPPINGCART.sHOPPINGCARTDo.TableName()
	_sHOPPINGCART.ALL = field.NewAsterisk(tableName)
	_sHOPPINGCART.ID = field.NewInt32(tableName, "ID")
	_sHOPPINGCART.STARTDATETIME = field.NewTime(tableName, "STARTDATETIME")
	_sHOPPINGCART.ENDDATETIME = field.NewTime(tableName, "ENDDATETIME")

	_sHOPPINGCART.fillFieldMap()

	return _sHOPPINGCART
}

type sHOPPINGCART struct {
	sHOPPINGCARTDo sHOPPINGCARTDo

	ALL           field.Asterisk
	ID            field.Int32
	STARTDATETIME field.Time
	ENDDATETIME   field.Time

	fieldMap map[string]field.Expr
}

func (s sHOPPINGCART) Table(newTableName string) *sHOPPINGCART {
	s.sHOPPINGCARTDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sHOPPINGCART) As(alias string) *sHOPPINGCART {
	s.sHOPPINGCARTDo.DO = *(s.sHOPPINGCARTDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sHOPPINGCART) updateTableName(table string) *sHOPPINGCART {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "ID")
	s.STARTDATETIME = field.NewTime(table, "STARTDATETIME")
	s.ENDDATETIME = field.NewTime(table, "ENDDATETIME")

	s.fillFieldMap()

	return s
}

func (s *sHOPPINGCART) WithContext(ctx context.Context) *sHOPPINGCARTDo {
	return s.sHOPPINGCARTDo.WithContext(ctx)
}

func (s sHOPPINGCART) TableName() string { return s.sHOPPINGCARTDo.TableName() }

func (s sHOPPINGCART) Alias() string { return s.sHOPPINGCARTDo.Alias() }

func (s sHOPPINGCART) Columns(cols ...field.Expr) gen.Columns {
	return s.sHOPPINGCARTDo.Columns(cols...)
}

func (s *sHOPPINGCART) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sHOPPINGCART) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 3)
	s.fieldMap["ID"] = s.ID
	s.fieldMap["STARTDATETIME"] = s.STARTDATETIME
	s.fieldMap["ENDDATETIME"] = s.ENDDATETIME
}

func (s sHOPPINGCART) clone(db *gorm.DB) sHOPPINGCART {
	s.sHOPPINGCARTDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sHOPPINGCART) replaceDB(db *gorm.DB) sHOPPINGCART {
	s.sHOPPINGCARTDo.ReplaceDB(db)
	return s
}

type sHOPPINGCARTDo struct{ gen.DO }

func (s sHOPPINGCARTDo) Debug() *sHOPPINGCARTDo {
	return s.withDO(s.DO.Debug())
}

func (s sHOPPINGCARTDo) WithContext(ctx context.Context) *sHOPPINGCARTDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sHOPPINGCARTDo) ReadDB() *sHOPPINGCARTDo {
	return s.Clauses(dbresolver.Read)
}

func (s sHOPPINGCARTDo) WriteDB() *sHOPPINGCARTDo {
	return s.Clauses(dbresolver.Write)
}

func (s sHOPPINGCARTDo) Session(config *gorm.Session) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Session(config))
}

func (s sHOPPINGCARTDo) Clauses(conds ...clause.Expression) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sHOPPINGCARTDo) Returning(value interface{}, columns ...string) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sHOPPINGCARTDo) Not(conds ...gen.Condition) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sHOPPINGCARTDo) Or(conds ...gen.Condition) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sHOPPINGCARTDo) Select(conds ...field.Expr) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sHOPPINGCARTDo) Where(conds ...gen.Condition) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sHOPPINGCARTDo) Order(conds ...field.Expr) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sHOPPINGCARTDo) Distinct(cols ...field.Expr) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sHOPPINGCARTDo) Omit(cols ...field.Expr) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sHOPPINGCARTDo) Join(table schema.Tabler, on ...field.Expr) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sHOPPINGCARTDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sHOPPINGCARTDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sHOPPINGCARTDo) RightJoin(table schema.Tabler, on ...field.Expr) *sHOPPINGCARTDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sHOPPINGCARTDo) Group(cols ...field.Expr) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sHOPPINGCARTDo) Having(conds ...gen.Condition) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sHOPPINGCARTDo) Limit(limit int) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sHOPPINGCARTDo) Offset(offset int) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sHOPPINGCARTDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sHOPPINGCARTDo) Unscoped() *sHOPPINGCARTDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sHOPPINGCARTDo) Create(values ...*model.SHOPPINGCART) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sHOPPINGCARTDo) CreateInBatches(values []*model.SHOPPINGCART, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sHOPPINGCARTDo) Save(values ...*model.SHOPPINGCART) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sHOPPINGCARTDo) First() (*model.SHOPPINGCART, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SHOPPINGCART), nil
	}
}

func (s sHOPPINGCARTDo) Take() (*model.SHOPPINGCART, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SHOPPINGCART), nil
	}
}

func (s sHOPPINGCARTDo) Last() (*model.SHOPPINGCART, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SHOPPINGCART), nil
	}
}

func (s sHOPPINGCARTDo) Find() ([]*model.SHOPPINGCART, error) {
	result, err := s.DO.Find()
	return result.([]*model.SHOPPINGCART), err
}

func (s sHOPPINGCARTDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SHOPPINGCART, err error) {
	buf := make([]*model.SHOPPINGCART, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sHOPPINGCARTDo) FindInBatches(result *[]*model.SHOPPINGCART, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sHOPPINGCARTDo) Attrs(attrs ...field.AssignExpr) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sHOPPINGCARTDo) Assign(attrs ...field.AssignExpr) *sHOPPINGCARTDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sHOPPINGCARTDo) Joins(fields ...field.RelationField) *sHOPPINGCARTDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sHOPPINGCARTDo) Preload(fields ...field.RelationField) *sHOPPINGCARTDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sHOPPINGCARTDo) FirstOrInit() (*model.SHOPPINGCART, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SHOPPINGCART), nil
	}
}

func (s sHOPPINGCARTDo) FirstOrCreate() (*model.SHOPPINGCART, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SHOPPINGCART), nil
	}
}

func (s sHOPPINGCARTDo) FindByPage(offset int, limit int) (result []*model.SHOPPINGCART, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sHOPPINGCARTDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sHOPPINGCARTDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sHOPPINGCARTDo) Delete(models ...*model.SHOPPINGCART) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sHOPPINGCARTDo) withDO(do gen.Dao) *sHOPPINGCARTDo {
	s.DO = *do.(*gen.DO)
	return s
}
