// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCARTITEM = "CART_ITEM"

// CARTITEM mapped from table <CART_ITEM>
type CARTITEM struct {
	ID              int32   `gorm:"column:ID;primaryKey" json:"ID"`
	SHOPPINGCARTID  int32   `gorm:"column:SHOPPING_CART_ID" json:"SHOPPING_CART_ID"`
	ACTION          string  `gorm:"column:ACTION" json:"ACTION"`
	STATUS          string  `gorm:"column:STATUS" json:"STATUS"`
	PRODUCTID       int32   `gorm:"column:PRODUCT_ID" json:"PRODUCT_ID"`
	QUANTITY        int32   `gorm:"column:QUANTITY" json:"QUANTITY"`
	ITEMPRICE       float32 `gorm:"column:ITEMPRICE" json:"ITEMPRICE"`
	ITEMTTOTALPRICE float32 `gorm:"column:ITEMTTOTALPRICE" json:"ITEMTTOTALPRICE"`
	ITEMTERM        int32   `gorm:"column:ITEMTERM" json:"ITEMTERM"`
}

// TableName CARTITEM's table name
func (*CARTITEM) TableName() string {
	return TableNameCARTITEM
}
