// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Shopping Cart -  Customization
 *
 *  The Shopping Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event.  Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase.  Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes the one-off fee such as the fee for handset and the recurring fee such as the fee of a network service.  Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated total items price including promotions.   Copyright  TM Forum 2019. All Rights Reserved   
 *
 * API version: 4.0.0
 */

package openapi


import (
	"time"
)



// TimePeriod - A period of time, either as a deadline (endDateTime only) a startDateTime only, or both
type TimePeriod struct {

	// End of the time period, using IETC-RFC-3339 format
	EndDateTime time.Time `json:"endDateTime,omitempty"`

	// Start of the time period, using IETC-RFC-3339 format. If you define a start, you must also define an end
	StartDateTime time.Time `json:"startDateTime,omitempty"`
}

// AssertTimePeriodRequired checks if the required fields are not zero-ed
func AssertTimePeriodRequired(obj TimePeriod) error {
	return nil
}

// AssertTimePeriodConstraints checks if the values respects the defined constraints
func AssertTimePeriodConstraints(obj TimePeriod) error {
	return nil
}
