// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Shopping Cart -  Customization
 *
 *  The Shopping Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event.  Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase.  Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes the one-off fee such as the fee for handset and the recurring fee such as the fee of a network service.  Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated total items price including promotions.   Copyright  TM Forum 2019. All Rights Reserved   
 *
 * API version: 4.0.0
 */

package openapi




// ProductTerm - Description of a productTerm linked to this product. This represent a commitment with a duration
type ProductTerm struct {

	// Description of the productTerm
	Description string `json:"description,omitempty"`

	// Name of the productTerm
	Name string `json:"name,omitempty"`

	Duration Quantity `json:"duration,omitempty"`

	ValidFor TimePeriod `json:"validFor,omitempty"`

	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`

	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation string `json:"@schemaLocation,omitempty"`

	// When sub-classing, this defines the sub-class entity name
	Type string `json:"@type,omitempty"`
}

// AssertProductTermRequired checks if the required fields are not zero-ed
func AssertProductTermRequired(obj ProductTerm) error {
	if err := AssertQuantityRequired(obj.Duration); err != nil {
		return err
	}
	if err := AssertTimePeriodRequired(obj.ValidFor); err != nil {
		return err
	}
	return nil
}

// AssertProductTermConstraints checks if the values respects the defined constraints
func AssertProductTermConstraints(obj ProductTerm) error {
	if err := AssertQuantityConstraints(obj.Duration); err != nil {
		return err
	}
	if err := AssertTimePeriodConstraints(obj.ValidFor); err != nil {
		return err
	}
	return nil
}
